# Generated by Django 4.2.3 on 2023-07-29 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documental',
        ),
    ]
