# Generated by Django 4.2.3 on 2023-07-29 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_delete_documental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='fecha',
        ),
    ]
