# Generated by Django 4.2.3 on 2023-07-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_documental_delete_plantaforma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documental',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='duracion',
        ),
        migrations.AddField(
            model_name='documental',
            name='plataforma',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='plataforma',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='serie',
            name='plataforma',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
